### PR TITLE
Feat: api aliases with tests for simplified api

### PR DESCRIPTION
**Pull request by patrickleet**
(from convo)
can we make ack true by default
opt-out instead
and, alias `queueName` with `command`, and alias `routingKey` with `event`

or `commandName` and `eventName`
it's hard to remember which goes with which
I think it would make the API look sexier and feel a little easier to use
```
export const command = 'context.domain.command'

export const listen = function (command, cb) {
  log.info('command handler for ', command.type)
  const { id, product } = command.data
  log.info({ id, product })
  cb()
}
```
```
export const event = 'context.domain.event'

export const subscribe = function (event, cb) {
  log.info('event handler for ', event.type)
  const { id, product } = event.data
  log.info({ id, product })
  cb()
}
```

### CODE REVIEW

**Comment by mateodelnorte** [comment]
Can you make some simple documentation for this?

**Comment by patrickleet** [comment]
@mateodelnorte done and done

**Comment by patrickleet** [comment]
pending another commit with new objectify-folder version

**Pull request merged**
